
install(TARGETS ${TARGET_NAME}.elf
        DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH} )

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.bin
              ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.map
        DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH} )

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/ DESTINATION
        ${INSTALL_DESTINATION}/${TARGET_PATH}/Sources)
