
install(TARGETS ${TARGET_NAME}.elf
        DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH} )

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.bin
              ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.map
        DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH} )

if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/src")
  install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/src
          DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH}
          PATTERN ".git" EXCLUDE )
else()
  install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/
          DESTINATION ${INSTALL_DESTINATION}/${TARGET_PATH}/src
          PATTERN ".git" EXCLUDE
          PATTERN "src" EXCLUDE )
endif()
