
install(TARGETS ${TARGET_NAME}.elf DESTINATION ${SEGASMP_DESTINATION}/${TARGET_PATH} )

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.bin
              ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.map
        DESTINATION ${SEGASMP_DESTINATION}/${TARGET_PATH} )

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/ DESTINATION ${SEGASMP_DESTINATION}/${TARGET_PATH}/Sources)
