set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_COLOR_DIAGNOSTICS ON)

set(GCC_STOP_ON_ERROR "-Wfatal-errors")

set( SEGALIB $ENV{SATURN_SBL}/segalib )
set( SEGASGL $ENV{SATURN_SGL} )

set( SATURN_ROOT $ENV{SATURN_ROOT} )
set( SATURN_COMMON $ENV{SATURN_COMMON} )
set( SATURN_CMAKE $ENV{SATURN_CMAKE} )

set(CMAKE_CXX_FLAGS "-fdiagnostics-color=always")
set(CMAKE_C_FLAGS "${GCC_STOP_ON_ERROR} -fdiagnostics-color=always")
set(CMAKE_AS_FLAGS "")
set(CMAKE_ASM_FLAGS "")

set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS} -g")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -g")
set(CMAKE_AS_FLAGS_DEBUG "${CMAKE_AS_FLAGS}")
set(CMAKE_ASM_FLAGS_DEBUG "${CMAKE_ASM_FLAGS}")

set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS} -Os")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -Os")
set(CMAKE_AS_FLAGS_RELEASE "${CMAKE_AS_FLAGS}")
set(CMAKE_ASM_FLAGS_RELEASE "${CMAKE_ASM_FLAGS}")

set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS} -Os -g")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS} -Os -g")
set(CMAKE_AS_FLAGS_RELWITHDEBINFO "${CMAKE_AS_FLAGS}")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "${CMAKE_ASM_FLAGS}")

set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS} -Os")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS} -Os")
set(CMAKE_AS_FLAGS_MINSIZEREL "${CMAKE_AS_FLAGS}")
set(CMAKE_ASM_FLAGS_MINSIZEREL "${CMAKE_ASM_FLAGS}")

set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_CXX_COMPILER $ENV{CXX})
set(CMAKE_AR $ENV{AR})
set(CMAKE_RANLIB $ENV{RANLIB})
set(CMAKE_ASM_COMPILER $ENV{AS})
set(CMAKE_LINKER $ENV{CC})
set(CMAKE_OBJCOPY $ENV{OBJCOPY})

set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> rv <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> rv <TARGET> <LINK_FLAGS> <OBJECTS>")

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <INCLUDES> <FLAGS> <SOURCE> -o <OBJECT>")
set(CMAKE_ASM_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})

set(CMAKE_MODULE_PATH $ENV{SATURN_CMAKE})
